### ISSUE TITLE
make a checklist for projects

### ISSUE THREAD

**Issue by afeld** [18F/open-source-policy#35]
Things like:
- [ ] A short, clear description for the uninitiated
- [ ] An entry in the [dashboard](https://18f.gsa.gov/dashboard/) (if applicable?)
- [ ] Our LICENSE and CONTRIBUTING files
- [ ] CI (if applicable)
- [ ] A glossary ([example](https://github.com/18F/save-ferris/wiki/Glossary))
- _etc._

/cc https://18f.github.io/open-source-program/pages/maintainer_guidelines/

**Comment by afeld** [comment]
* [ ] easy setup (as a script or otherwise) – https://github.com/18F/open-source-program/issues/62

**Comment by cmc333333** [comment]
CFPB had a nice checklist, but I don't remember if it was ever published.

@ascott1 @contolini @marcesher ?

**Comment by ascott1** [comment]
Here's the CFPB list:

- [ ] **Has PII been removed?**
  - Use [Clouseau](https://github.com/virtix/clouseau) for scanning source code.
  - If there are images, visually inspect each image to ensure there is no CFPB-specific information.
- [ ] **Have security vulnerabilities been remediated?**
- [ ] **Are we including any other open source products? If so, is there any conflict with our public domain release?**
- [ ] **Is our `TERMS.md` included?**
- [ ] **Is a `CHANGELOG.md` present and does it contain structured, consistently formatted recent history?**
- [ ] **Are instructions for contributing included (`CONTRIBUTING.md`)?**
- [ ] **Are installation instructions clearly written in the `README` _and_ tested on a clean machine?**
- [ ] **Are all dependencies described in the `README`, `requirements.txt`, and/or `buildout.cfg`?**
- [ ] **Are the API docs generated?**
- [ ] **Are there unit tests?**
- [ ] **If applicable and possible, is it set up in TravisCI?**
- [ ] **Have multiple people reviewed the code?**
- [ ] **Is there a screenshot in the `README`, if applicable?**

**Comment by gbinal** [comment]
Here's the link - https://github.com/cfpb/open-source-project-template/blob/master/opensource-checklist.md

**Comment by afeld** [comment]
We now have some combination of this:

* https://pages.18f.gov/before-you-ship/
* https://pages.18f.gov/open-source-guide/

**Comment by debbryant** [comment]
So… wrt to this

List the licensing information for your project.
This part of the repo should answer the question: What is the license for this project? All 18F projects are developed in the international public domain whenever possible and contain a LICENSE.md <https://github.com/18F/open-source-policy/blob/master/LICENSE.md>document, as well as a paragraph at the end of each README which contains information about the public domain. We post this information in the README <https://github.com/18F/18f.gsa.gov#public-domain>, so that users know the code can be adapted and reused, and so they can easily see this information instead of going to a second site.

—

It’s not suggested that Public Domain is a software license is it?

Deb

**Comment by konklone** [comment]
Hi @debbryant -- we're not suggesting that "public domain" is a software license. Occasionally, our repos have a license (not public domain) when we're forking or modifying some externally licensed code. And in practice, we want to use the `LICENSE` naming convention that GitHub and others look for no matter what we use.

Our general approach is to apply the CC0 public domain dedication in international contexts. CC0 does technically contain a "fallback license" for countries that have no concept of the public domain, a license which tries to create a legal state that resembles our concept of the public domain as closely as possible.

However, in general we do try to talk about public domain dedications and not licenses. I'm sure we have various slips throughout our blog posts and documents, since it's honestly pretty confusing.

**Comment by afeld** [comment]
Closing as stale.
